### PR TITLE
Separating Frontend and Backend Functionality in NDT HTML5 Client - Part 2

### PR DESCRIPTION
**Pull request by shredtechular**
**NOTE** - this PR is dependent on #54 and will need to be rebased after #54 is reviewed/accepted.

Per feedback contained in #49 this PR is part 2 of spliting the changes in that PR into a more manageable PR.  This first PR contains additional cleanup of the script.js file adding in comments that follow [Google JS Code Style](https://google.github.io/styleguide/javascriptguide.xml).

Once #54 and this PR is merged, #49 can be closed.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt/55)

### CODE REVIEW

**Comment by collina** [comment]
Aren't private variables typically denoted with prefixed underscores rather than appended ones? http://stackoverflow.com/questions/4484424/underscore-prefix-for-property-and-method-names-in-javascriptfe

<details><summary><i>Previously, shredtechular (Andrew Newhouse) wrote…</i></summary>
> #### Separating Frontend and Backend Functionality in NDT HTML5 Client \- Part 2
> 
> **NOTE** - this PR is dependent on #54 and will need to be rebased after #54 is reviewed/accepted.
> 
> 
> 
> Per feedback contained in #49 this PR is part 2 of spliting the changes in that PR into a more manageable PR.  This first PR contains additional cleanup of the script.js file adding in comments that follow [Google JS Code Style](https://google.github.io/styleguide/javascriptguide.xml).
> 
> 
> 
> Once #54 and this PR is merged, #49 can be closed.
> 
> 
> 
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt/55#-:-KJHsTxYc0JS6uolscGX:-1855016248)*

**Comment by collina** [comment]
Are all of this methods actually private that are specified as such (e.g. testStatus)? 

<details><summary><i>Previously, collina (Collin Anderson) wrote…</i></summary>
> Aren't private variables typically denoted with prefixed underscores rather than appended ones? http://stackoverflow.com/questions/4484424/underscore-prefix-for-property-and-method-names-in-javascriptfe
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt/55#-:-KJHvtXJjD389ExERl_C:1554374217)*

**Comment by shredtechular** [comment]
I thought it was weird to put them as "appended" vs. prepended.  However, the Google JS Style guide says, "trailing" and even shows examples of them being appended?  Am I misunderstanding?

"Private properties and methods should be named with a trailing underscore.
Protected properties and methods should be named without a trailing underscore (like public ones)."

https://google.github.io/styleguide/javascriptguide.xml?showone=Code_formatting#Naming

Also, "We recommend the use of the JSDoc annotations @private and @protected to indicate visibility levels for classes, functions, and properties."

https://google.github.io/styleguide/javascriptguide.xml?showone=Code_formatting#Visibility__private_and_protected_fields_

<details><summary><i>Previously, collina (Collin Anderson) wrote…</i></summary>
> Are all of this methods actually private that are specified as such (e.g. testStatus)? 
</details>


---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt/55#-:-KJpeZ-bEEznjIJ3MoHq:-1299914725)*

**Comment by collina** [comment]
Yeah you are right, that's strange but okay.

<details><summary><i>Previously, shredtechular (Andrew Newhouse) wrote…</i></summary>
> I thought it was weird to put them as "appended" vs. prepended.  However, the Google JS Style guide says, "trailing" and even shows examples of them being appended?  Am I misunderstanding?
> 
> "Private properties and methods should be named with a trailing underscore.
> Protected properties and methods should be named without a trailing underscore (like public ones)."
> 
> https://google.github.io/styleguide/javascriptguide.xml?showone=Code_formatting#Naming
> 
> Also, "We recommend the use of the JSDoc annotations @private and @protected to indicate visibility levels for classes, functions, and properties."
> 
> https://google.github.io/styleguide/javascriptguide.xml?showone=Code_formatting#Visibility__private_and_protected_fields_
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt/55#-:-KJpnqvK7TzZmYsvJO7V:1210781125)*

**Comment by shredtechular** [comment]
Closing out in favor of #55

**Pull request closed without merging**
